[package]
name = "rustiness"
version = "0.1.0"
authors = ["Brandon Lin <brandbest1@gmail.com>"]
edition = "2018"

[dependencies]
bitfield = "0.13.2"
strum = "0.18.0"
strum_macros = "0.18.0"
sdl2 = "0.34"