use strum_macros::Display;

#[derive(Debug, Ord, PartialOrd, Eq, PartialEq, Display)]
pub enum Opcode {
    // Storage
    LDA,
    LDX,
    LDY,
    STA,
    STX,
    STY,
    TAX,
    TAY,
    TSX,
    TXA,
    TXS,
    TYA,
    // Math
    ADC,
    DEC,
    DEX,
    DEY,
    INC,
    INX,
    INY,
    SBC,
    // Bitwise
    AND,
    ASL,
    BIT,
    EOR,
    LSR,
    ORA,
    ROL,
    ROR,
    // Branch
    BCC,
    BCS,
    BEQ,
    BMI,
    BNE,
    BPL,
    BVC,
    BVS,
    // Jump
    JMP,
    JSR,
    RTI,
    RTS,
    // Regs
    CLC,
    CLD,
    CLI,
    CLV,
    CMP,
    CPX,
    CPY,
    SEC,
    SED,
    SEI,
    // Stack
    PHA,
    PHP,
    PLA,
    PLP,
    // etc.
    BRK,
    NOP,
}

#[derive(Debug, Copy, Clone, Ord, PartialOrd, Eq, PartialEq, Display)]
pub enum AddressingMode {
    Abs,
    AbsX,
    AbsY,
    Ind,
    IndX,
    IndY,
    Zpg,
    ZpgX,
    ZpgY,
    // Others
    Imm,
    Acc,
    Imp,
    Rel,
}

use AddressingMode::*;
use Opcode::*;

#[allow(dead_code)]
pub const OPCODE_MATRIX: [[Option<(Opcode, AddressingMode, u8)>; 0x10]; 0x10] = [
    [
        Some((BRK, Imp, 7)),
        Some((ORA, IndX, 6)),
        None,
        None,
        None,
        Some((ORA, Zpg, 3)),
        Some((ASL, Zpg, 5)),
        None,
        Some((PHP, Imp, 3)),
        Some((ORA, Imm, 2)),
        Some((ASL, Acc, 2)),
        None,
        None,
        Some((ORA, Abs, 4)),
        Some((ASL, Abs, 6)),
        None,
    ],
    [
        Some((BPL, Rel, 2)),
        Some((ORA, IndY, 5)),
        None,
        None,
        None,
        Some((ORA, ZpgX, 4)),
        Some((ASL, ZpgX, 6)),
        None,
        Some((CLC, Imp, 2)),
        Some((ORA, AbsY, 4)),
        None,
        None,
        None,
        Some((ORA, AbsX, 4)),
        Some((ASL, AbsX, 7)),
        None,
    ],
    [
        Some((JSR, Abs, 6)),
        Some((AND, IndX, 6)),
        None,
        None,
        Some((BIT, Zpg, 3)),
        Some((AND, Zpg, 3)),
        Some((ROL, Zpg, 5)),
        None,
        Some((PLP, Imp, 4)),
        Some((AND, Imm, 2)),
        Some((ROL, Acc, 2)),
        None,
        Some((BIT, Abs, 4)),
        Some((AND, Abs, 4)),
        Some((ROL, Abs, 6)),
        None,
    ],
    [
        Some((BMI, Rel, 2)),
        Some((AND, IndY, 5)),
        None,
        None,
        None,
        Some((AND, ZpgX, 4)),
        Some((ROL, ZpgX, 6)),
        None,
        Some((SEC, Imp, 2)),
        Some((AND, AbsY, 4)),
        None,
        None,
        None,
        Some((AND, AbsX, 4)),
        Some((ROL, AbsX, 7)),
        None,
    ],
    [
        Some((RTI, Imp, 6)),
        Some((EOR, IndX, 6)),
        None,
        None,
        None,
        Some((EOR, Zpg, 3)),
        Some((LSR, Zpg, 5)),
        None,
        Some((PHA, Imp, 3)),
        Some((EOR, Imm, 2)),
        Some((LSR, Acc, 2)),
        None,
        Some((JMP, Abs, 3)),
        Some((EOR, Abs, 4)),
        Some((LSR, Abs, 6)),
        None,
    ],
    [
        Some((BVC, Rel, 2)),
        Some((EOR, IndY, 5)),
        None,
        None,
        None,
        Some((EOR, ZpgX, 4)),
        Some((LSR, ZpgX, 6)),
        None,
        Some((CLI, Imp, 2)),
        Some((EOR, AbsY, 4)),
        None,
        None,
        None,
        Some((EOR, AbsX, 4)),
        Some((LSR, AbsX, 7)),
        None,
    ],
    [
        Some((RTS, Imp, 6)),
        Some((ADC, IndX, 6)),
        None,
        None,
        None,
        Some((ADC, Zpg, 3)),
        Some((ROR, Zpg, 5)),
        None,
        Some((PLA, Imp, 4)),
        Some((ADC, Imm, 2)),
        Some((ROR, Acc, 2)),
        None,
        Some((JMP, Ind, 5)),
        Some((ADC, Abs, 4)),
        Some((ROR, Abs, 6)),
        None,
    ],
    [
        Some((BVS, Rel, 2)),
        Some((ADC, IndY, 5)),
        None,
        None,
        None,
        Some((ADC, ZpgX, 4)),
        Some((ROR, ZpgX, 6)),
        None,
        Some((SEI, Imp, 2)),
        Some((ADC, AbsY, 4)),
        None,
        None,
        None,
        Some((ADC, AbsX, 4)),
        Some((ROR, AbsX, 7)),
        None,
    ],
    [
        None,
        Some((STA, IndX, 6)),
        None,
        None,
        Some((STY, Zpg, 3)),
        Some((STA, Zpg, 3)),
        Some((STX, Zpg, 3)),
        None,
        Some((DEY, Imp, 2)),
        None,
        Some((TXA, Imp, 2)),
        None,
        Some((STY, Abs, 4)),
        Some((STA, Abs, 4)),
        Some((STX, Abs, 4)),
        None,
    ],
    [
        Some((BCC, Rel, 2)),
        Some((STA, IndY, 6)),
        None,
        None,
        Some((STY, ZpgX, 4)),
        Some((STA, ZpgX, 4)),
        Some((STX, ZpgY, 4)),
        None,
        Some((TYA, Imp, 2)),
        Some((STA, AbsY, 5)),
        Some((TXS, Imp, 2)),
        None,
        None,
        Some((STA, AbsX, 5)),
        None,
        None,
    ],
    [
        Some((LDY, Imm, 2)),
        Some((LDA, IndX, 6)),
        Some((LDX, Imm, 2)),
        None,
        Some((LDY, Zpg, 3)),
        Some((LDA, Zpg, 3)),
        Some((LDX, Zpg, 3)),
        None,
        Some((TAY, Imp, 2)),
        Some((LDA, Imm, 2)),
        Some((TAX, Imp, 2)),
        None,
        Some((LDY, Abs, 4)),
        Some((LDA, Abs, 4)),
        Some((LDX, Abs, 4)),
        None,
    ],
    [
        Some((BCS, Rel, 2)),
        Some((LDA, IndY, 5)),
        None,
        None,
        Some((LDY, ZpgX, 4)),
        Some((LDA, ZpgX, 4)),
        Some((LDX, ZpgY, 4)),
        None,
        Some((CLV, Imp, 2)),
        Some((LDA, AbsY, 4)),
        Some((TSX, Imp, 2)),
        None,
        Some((LDY, AbsX, 4)),
        Some((LDA, AbsX, 4)),
        Some((LDX, AbsY, 4)),
        None,
    ],
    [
        Some((CPY, Imm, 2)),
        Some((CMP, IndX, 6)),
        None,
        None,
        Some((CPY, Zpg, 3)),
        Some((CMP, Zpg, 3)),
        Some((DEC, Zpg, 5)),
        None,
        Some((INY, Imp, 2)),
        Some((CMP, Imm, 2)),
        Some((DEX, Imp, 2)),
        None,
        Some((CPY, Abs, 4)),
        Some((CMP, Abs, 4)),
        Some((DEC, Abs, 6)),
        None,
    ],
    [
        Some((BNE, Rel, 2)),
        Some((CMP, IndY, 5)),
        None,
        None,
        None,
        Some((CMP, ZpgX, 4)),
        Some((DEC, ZpgX, 6)),
        None,
        Some((CLD, Imp, 2)),
        Some((CMP, AbsY, 4)),
        None,
        None,
        None,
        Some((CMP, AbsX, 4)),
        Some((DEC, AbsX, 7)),
        None,
    ],
    [
        Some((CPX, Imm, 2)),
        Some((SBC, IndX, 6)),
        None,
        None,
        Some((CPX, Zpg, 3)),
        Some((SBC, Zpg, 3)),
        Some((INC, Zpg, 5)),
        None,
        Some((INX, Imp, 2)),
        Some((SBC, Imm, 2)),
        Some((NOP, Imp, 2)),
        None,
        Some((CPX, Abs, 4)),
        Some((SBC, Abs, 4)),
        Some((INC, Abs, 6)),
        None,
    ],
    [
        Some((BEQ, Rel, 2)),
        Some((SBC, IndY, 5)),
        None,
        None,
        None,
        Some((SBC, ZpgX, 4)),
        Some((INC, ZpgX, 6)),
        None,
        Some((SED, Imp, 2)),
        Some((SBC, AbsY, 4)),
        None,
        None,
        None,
        Some((SBC, AbsX, 4)),
        Some((INC, AbsX, 7)),
        None,
    ],
];
